version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    hostname: aktk.local
    volumes:
      - ./www:/var/www/html
    #ports:
    #  - "8000:80"
    restart: always
    environment:
      VIRTUAL_HOST: aktk.local
      #VIRTUAL_PORT: 8003
      #LETSENCRYPT_HOST: aktk.local
      #LETSENCRYPT_EMAIL: aktk@aktk.local
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
networks:
  default:
    external:
      name: aktk_local