version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    hostname: aktk.lo
    volumes:
      - ./www:/var/www/html
      - ./php/ini/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
    external_links:
      - mysql
    environment:
      VIRTUAL_HOST: aktk.lo
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: aktk

networks:
  default:
    external:
      name: nginxproxy_default