version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    hostname: aktk.local
    volumes:
      - ./www:/var/www/html
    #ports:
    #  - "8000:80"
    restart: always
    external_links:
      - mysql
    environment:
      VIRTUAL_HOST: aktk.local
      #VIRTUAL_PORT: 8003
      #LETSENCRYPT_HOST: aktk.local
      #LETSENCRYPT_EMAIL: aktk@aktk.local
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: aktk

networks:
  default:
    external:
      name: aktk_local